name: deploy on FTP
on:
  push:
      branches:  
        -main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1
    - name: Deploy app
      uses: sebastianpopp/git-ftp-action@releases/v3
      with: 
        url: "s1.ct8.pl/domains/julita.ct8.pl/public_html/wp-content/themes/moj_szablon"
        user: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        
