name: deploy on FTP
on: 
  push:
    branches:
      - main
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy app
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:  
        server: "s1.ct8.pl"
        server-dir: "./domains/julita.ct8.pl/public_html/wp-content/themes/moj_szablon/"
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
